// <auto-generated>
// Rewired Constants
// This list was generated on 2/5/2023 1:19:45 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Forward")]
        public const int MoveForward = 6;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Strafe")]
        public const int Strafe = 1;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Vertical")]
        public const int LookVertical = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Horizontal")]
        public const int LookHorizontal = 3;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Interact")]
        public const int Interact = 4;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Attack")]
        public const int Attack = 5;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIHorizontal")]
        public const int UIHorizontal = 7;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIVertical")]
        public const int UIVertical = 8;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UICancel")]
        public const int UICancel = 9;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UISubmit")]
        public const int UISubmit = 10;
        
    }
}
